//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyDescription("SgAlpha2")]
[assembly: System.Reflection.AssemblyTitle("SgAlpha2")]
[assembly: System.Reflection.AssemblyProduct("SgAlpha2 Debug 0.0.0.1")]
[assembly: System.Reflection.AssemblyVersion("0.0.0.1")]


